hugoblox:
  schema: "2.0"
  identity:
    name: Yifei Wang
    type: person
    tagline: AI Researcher | Biogen
    description: "Dr. Yifei Wang is now a machine learning research follow at Biogen, focusing on AI-aided drug design. "
    organization: Biogen
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  seo:
    title: Yifei Wang | AI for drug discovery | Biogen
    location:
      address:
        city: Cambridge
        region: MA
        postal_code: "02142"
        country: US
